spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27018/customer-dev?authSource=admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
springdoc:
  swagger-ui:
    path: /swagger-ui.html
