global:
  message: Welcome to Customer Service dev environment
server:
  port: 8082
spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/customer-dev?authSource=admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
springdoc:
  swagger-ui:
    path: /swagger-ui.html  
  
