global:
  message: Welcome to Order Service dev environment
server:
  port: 8082
spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27018/product-service?authSource=admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
springdoc:
  swagger-ui:
    path: /swagger-ui.html  
  
